---
## This is unused as prettier seems to have broken many plugins as of 240930
## values set by .editorconfig
arrowParens: 'always'
bracketSameLine: false
bracketSpacing: false
endOfLine: lf
experimentalTernaries: true
jsxSingleQuote: false
printWidth: 120
quoteProps: 'as-needed'
semi: false
singleQuote: true
tabWidth: 4
trailingComma: 'es5'
useTabs: false
